## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load the Dataset

In [3]:

df = pd.read_csv("messy_ecommerce_data.csv")

df.head()

,Customer_ID,Customer_Name,Gender,Country,City,Category,Product,Quantity,Unit_Price,Order_Date,Payment_Method,Rating,Discount,Total_Amount
0,C1079,Emma Malik,Female,Pakistan,Hyderabad,Books,Python Book,2.0,$620.87,2025-11-01,Credit Card,1.0,0.14,1067.90
1,C1290,fatima shah,Male,India,Delhi,Clothing,T-Shirt,NaN,NaN,2025-11-30,PayPal,2.0,0.30,354.96
2,C1075,John Lohano,Female,UK,London,Books,ML Book,2.0,581.54,2025-05-09,Bank Transfer,2.0,0.26,860.68
3,C1611,Emma Brown,NaN,Pakistan,Jamshoro,Home & Kitchen,Cookware Set,4.0,$1315.82,2025-08-07,Credit Card,1.0,0.28,3789.56
4,C1376,Usman Lohano,Female,India,Mumbai,Electronics,Mouse,-5.0,185.56,2024-01-08,PayPal,2.0,0.21,732.96

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.shape

Rows: 675
Columns: 14

(675, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 675 entries, 0 to 674
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     673 non-null    object
 1   Customer_Name   660 non-null    object
 2   Gender          651 non-null    object
 3   Country         657 non-null    object
 4   City            660 non-null    object
 5   Category        661 non-null    object
 6   Product         663 non-null    object
 7   Quantity        660 non-null    float64
 8   Unit_Price      660 non-null    object
 9   Order_Date      662 non-null    object
 10  Payment_Method  658 non-null    object
 11  Rating          653 non-null    float64
 12  Discount        660 non-null    float64
 13  Total_Amount    664 non-null    float64
dtypes: float64(4), object(10)
memory usage: 74.0+ KB

In [6]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Customer_ID,673,653,C1157,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_Name,660,176,John Ahmed,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,651,12,Male,303,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,657,28,USA,107,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,660,40,Abu Dhabi,39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,661,19,Electronics,143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product,663,25,Laptop,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,660.0,NaN,NaN,NaN,2.936364,1.541203,-5.0,2.0,3.0,4.0,5.0
Unit_Price,660,633,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order_Date,662,429,2024-11-03,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment_Method,658,14,Bank Transfer,141,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rating,653.0,NaN,NaN,NaN,3.026034,1.521098,-2.0,2.0,3.0,4.0,10.0
Discount,660.0,NaN,NaN,NaN,0.159379,0.176032,-0.25,0.07,0.14,0.22,3.0
Total_Amount,664.0,NaN,NaN,NaN,4195.210617,43289.049372,-1000.0,722.6825,1533.565,2891.6475,999999.0

In [7]:
df.isnull().sum()

Customer_ID        2
Customer_Name     15
Gender            24
Country           18
City              15
Category          14
Product           12
Quantity          15
Unit_Price        15
Order_Date        13
Payment_Method    17
Rating            22
Discount          15
Total_Amount      11
dtype: int64

## Data Quality Report — Before Cleaning

In [8]:
numeric_columns = [
    "Quantity",
    "Unit_Price",
    "Rating",
    "Discount",
    "Total_Amount"
]

quality_report = pd.DataFrame({
    "Column": df.columns,
    "Null_Count": df.isnull().sum().values,
    "Data_Type": df.dtypes.astype(str).values,
    "Unique_Values": df.nunique().values
})

quality_report["Null_Percentage"] = (
    quality_report["Null_Count"] / len(df) * 100
).round(2)

quality_report

            Column  Null_Count Data_Type  Unique_Values  Null_Percentage
0      Customer_ID           2    object            653             0.30
1    Customer_Name          15    object            176             2.22
2           Gender          24    object             12             3.56
3          Country          18    object             28             2.67
4             City          15    object             40             2.22
5         Category          14    object             19             2.07
6          Product          12    object             25             1.78
7         Quantity          15   float64             11             2.22
8       Unit_Price          15    object            633             2.22
9       Order_Date          13    object            429             1.93
10  Payment_Method          17    object             14             2.52
11          Rating          22   float64             13             3.26
12        Discount          15   float64             39             2.22
13    Total_Amount          11   float64            637             1.63

In [9]:
print("Duplicate rows:", df.duplicated().sum())

df[numeric_columns].apply(pd.to_numeric, errors="coerce").describe().T

Duplicate rows: 20

,count,mean,std,min,25%,50%,75%,max
Quantity,660.0,2.936364,1.541203,-5.00,2.0000,3.000,4.0000,5.0
Unit_Price,574.0,1384.870714,6116.131458,-100.00,369.3975,743.595,1136.5500,100000.0
Rating,653.0,3.026034,1.521098,-2.00,2.0000,3.000,4.0000,10.0
Discount,660.0,0.159379,0.176032,-0.25,0.0700,0.140,0.2200,3.0
Total_Amount,664.0,4195.210617,43289.049372,-1000.00,722.6825,1533.565,2891.6475,999999.0

In [10]:
before_rows = len(df)
before_duplicates = df.duplicated().sum()
before_nulls = df.isnull().sum().sum()

before_summary = pd.DataFrame({
    "Metric": [
        "Row Count",
        "Duplicate Rows",
        "Total Null Values",
        "Number of Columns"
    ],
    "Before Cleaning": [
        before_rows,
        before_duplicates,
        before_nulls,
        df.shape[1]
    ]
})

before_summary

              Metric  Before Cleaning
0          Row Count              675
1     Duplicate Rows               20
2  Total Null Values              208
3  Number of Columns               14

## Clean Text Formatting

In [ ]:
text_columns = [
    "Customer_ID",
    "Customer_Name",
    "Gender",
    "Country",
    "City",
    "Category",
    "Product",
    "Payment_Method"
]

for col in text_columns:
    df[col] = df[col].astype("string").str.strip()

##  Standardize Gender

In [ ]:
gender_map = {
    "male": "Male",
    "MALE": "Male",
    "M": "Male",
    "Female": "Female",
    "female": "Female",
    "FEMALE": "Female",
    "F": "Female"
}

df["Gender"] = df["Gender"].replace(gender_map)
df["Gender"] = df["Gender"].replace({
    "Malee": np.nan,
    "Fem": np.nan,
    "unknown": np.nan,
    "Unknown": np.nan
})

df["Gender"].value_counts(dropna=False)

## Standardize Country

In [ ]:
country_map = {
    "pakistan": "Pakistan",
    "PAKISTAN": "Pakistan",
    "India": "India",
    "india": "India",
    "INDIA": "India",
    "USA": "USA",
    "usa": "USA",
    "U.S.A": "USA",
    "United States": "USA",
    "UK": "UK",
    "uk": "UK",
    "U.K.": "UK",
    "United Kingdom": "UK",
    "Canada": "Canada",
    "canada": "Canada",
    "CANADA": "Canada",
    "UAE": "UAE",
    "uae": "UAE",
    "U.A.E.": "UAE",
    "United Arab Emirates": "UAE",
    "Pak": "Pakistan",
    "Pak ": "Pakistan",
    "USAa": "USA"
}

df["Country"] = df["Country"].replace(country_map)
df["Country"] = df["Country"].replace(
    ["Unknown", "unknown", "N/A", "NIL", "Invalid", "?"],
    np.nan
)

df["Country"].value_counts(dropna=False)

## Standardize Category and Payment Method

In [11]:
df["Category"] = (
    df["Category"]
    .astype("string")
    .str.strip()
    .str.lower()
    .replace({
        "electronics": "Electronics",
        "clothing": "Clothing",
        "home & kitchen": "Home & Kitchen",
        "books": "Books",
        "sports": "Sports",
        "unknown": np.nan,
        "n/a": np.nan,
        "other": np.nan,
        "x": np.nan,
        "invalid": np.nan,
        "-": np.nan,
        "none": np.nan,
        "?": np.nan
    })
)

payment_map = {
    "cash": "Cash",
    "credit card": "Credit Card",
    "debit card": "Debit Card",
    "paypal": "PayPal",
    "bank transfer": "Bank Transfer"
}

df["Payment_Method"] = (
    df["Payment_Method"]
    .astype("string")
    .str.strip()
    .str.lower()
    .replace(payment_map)
)

df["Payment_Method"] = df["Payment_Method"].replace(
    ["unknown", "n/a", "nil", "invalid", "?"],
    np.nan
)

##  Standardize Names and Cities

In [12]:
df["Customer_Name"] = (
    df["Customer_Name"]
    .astype("string")
    .str.strip()
    .str.title()
)

df["City"] = (
    df["City"]
    .astype("string")
    .str.strip()
    .str.title()
)

## Correct Numeric Data Types

In [13]:
df["Quantity"] = pd.to_numeric(
    df["Quantity"], errors="coerce"
)

df["Unit_Price"] = (
    df["Unit_Price"]
    .astype("string")
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["Unit_Price"] = pd.to_numeric(
    df["Unit_Price"], errors="coerce"
)

df["Rating"] = pd.to_numeric(
    df["Rating"], errors="coerce"
)

df["Discount"] = pd.to_numeric(
    df["Discount"], errors="coerce"
)

df["Total_Amount"] = pd.to_numeric(
    df["Total_Amount"], errors="coerce"
)

In [14]:
df.loc[df["Quantity"] <= 0, "Quantity"] = np.nan
df.loc[df["Unit_Price"] <= 0, "Unit_Price"] = np.nan
df.loc[~df["Rating"].between(1, 5), "Rating"] = np.nan
df.loc[~df["Discount"].between(0, 1), "Discount"] = np.nan
df.loc[df["Total_Amount"] < 0, "Total_Amount"] = np.nan

## 14. Correct Date Format

The dataset contains several date formats. We convert the date column into one consistent datetime format.

`dayfirst=True` helps interpret dates such as `25/03/2024`.

In [15]:
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    errors="coerce",
    dayfirst=True
)

df["Order_Date"].head()

0   2025-01-11
1          NaT
2   2025-09-05
3   2025-07-08
4   2024-08-01
Name: Order_Date, dtype: datetime64[ns]

## Remove Duplicate Rows

In [16]:
duplicates_removed = df.duplicated().sum()

df = df.drop_duplicates().reset_index(drop=True)

print("Duplicate rows removed:", duplicates_removed)
print("Rows after duplicate removal:", len(df))

Duplicate rows removed: 20
Rows after duplicate removal: 655

In [17]:
categorical_columns = [
    "Customer_Name",
    "Gender",
    "Country",
    "City",
    "Category",
    "Product",
    "Payment_Method"
]

numeric_columns = [
    "Quantity",
    "Unit_Price",
    "Rating",
    "Discount",
    "Total_Amount"
]

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

df["Order_Date"] = df["Order_Date"].ffill()

print("Remaining missing values:")
print(df.isnull().sum())

Remaining missing values:
Customer_ID       2
Customer_Name     0
Gender            0
Country           0
City              0
Category          0
Product           0
Quantity          0
Unit_Price        0
Order_Date        0
Payment_Method    0
Rating            0
Discount          0
Total_Amount      0
dtype: int64

## Correct Final Data Types

In [18]:
df["Customer_ID"] = (
    df["Customer_ID"]
    .astype("string")
    .str.strip()
    .str.upper()
)

df["Quantity"] = df["Quantity"].round().astype("int64")
df["Unit_Price"] = df["Unit_Price"].astype("float64")
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Rating"] = df["Rating"].round().astype("int64")
df["Discount"] = df["Discount"].astype("float64")
df["Total_Amount"] = df["Total_Amount"].astype("float64")

## Validate the Cleaned Dataset

In [19]:
print("Shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Shape: (655, 14)

Missing values:
Customer_ID       2
Customer_Name     0
Gender            0
Country           0
City              0
Category          0
Product           0
Quantity          0
Unit_Price        0
Order_Date        0
Payment_Method    0
Rating            0
Discount          0
Total_Amount      0
dtype: int64

Duplicate rows: 3

Data types:
Customer_ID       string[python]
Customer_Name     string[python]
Gender                    object
Country                   object
City              string[python]
Category          string[python]
Product                   object
Quantity                   int64
Unit_Price               float64
Order_Date        datetime64[ns]
Payment_Method    string[python]
Rating                     int64
Discount                 float64
Total_Amount             float64
dtype: object

In [20]:
print("Quantity range:", df["Quantity"].min(), "to", df["Quantity"].max())
print("Unit Price range:", df["Unit_Price"].min(), "to", df["Unit_Price"].max())
print("Rating range:", df["Rating"].min(), "to", df["Rating"].max())
print("Discount range:", df["Discount"].min(), "to", df["Discount"].max())
print("Total Amount range:", df["Total_Amount"].min(), "to", df["Total_Amount"].max())

Quantity range: 1 to 5
Unit Price range: 1.0 to 100000.0
Rating range: 1 to 5
Discount range: 0.0 to 0.3
Total Amount range: 0.0 to 999999.0

## Before Vs After

In [21]:
after_rows = len(df)
after_duplicates = df.duplicated().sum()
after_nulls = df.isnull().sum().sum()

summary = pd.DataFrame({
    "Metric": [
        "Row Count",
        "Duplicate Rows",
        "Total Null Values",
        "Number of Columns"
    ],
    "Before Cleaning": [
        before_rows,
        before_duplicates,
        before_nulls,
        df.shape[1]
    ],
    "After Cleaning": [
        after_rows,
        after_duplicates,
        after_nulls,
        df.shape[1]
    ]
})

summary

              Metric  Before Cleaning  After Cleaning
0          Row Count              675             655
1     Duplicate Rows               20               3
2  Total Null Values              208               2
3  Number of Columns               14              14

In [22]:
expected_dtypes = {
    "Customer_ID": "string",
    "Customer_Name": "string",
    "Gender": "string",
    "Country": "string",
    "City": "string",
    "Category": "string",
    "Product": "string",
    "Quantity": "int64",
    "Unit_Price": "float64",
    "Order_Date": "datetime64[ns]",
    "Payment_Method": "string",
    "Rating": "int64",
    "Discount": "float64",
    "Total_Amount": "float64"
}

dtype_summary = pd.DataFrame({
    "Column": df.columns,
    "Actual_Dtype": [str(df[col].dtype) for col in df.columns],
    "Expected_Dtype": [expected_dtypes[col] for col in df.columns]
})

dtype_summary["Correct"] = (
    dtype_summary["Actual_Dtype"] == dtype_summary["Expected_Dtype"]
)

dtype_summary

            Column    Actual_Dtype  Expected_Dtype  Correct
0      Customer_ID          string          string     True
1    Customer_Name          string          string     True
2           Gender          object          string    False
3          Country          object          string    False
4             City          string          string     True
5         Category          string          string     True
6          Product          object          string    False
7         Quantity           int64           int64     True
8       Unit_Price         float64         float64     True
9       Order_Date  datetime64[ns]  datetime64[ns]     True
10  Payment_Method          string          string     True
11          Rating           int64           int64     True
12        Discount         float64         float64     True
13    Total_Amount         float64         float64     True

In [23]:
df.head(10)

,Customer_ID,Customer_Name,Gender,Country,City,Category,Product,Quantity,Unit_Price,Order_Date,Payment_Method,Rating,Discount,Total_Amount
0,C1079,Emma Malik,Female,Pakistan,Hyderabad,Books,Python Book,2,620.870,2025-01-11,Credit Card,1,0.14,1067.90
1,C1290,Fatima Shah,Male,India,Delhi,Clothing,T-Shirt,3,756.275,2025-01-11,PayPal,2,0.30,354.96
2,C1075,John Lohano,Female,UK,London,Books,ML Book,2,581.540,2025-09-05,Bank Transfer,2,0.26,860.68
3,C1611,Emma Brown,Male,Pakistan,Jamshoro,Home & Kitchen,Cookware Set,4,1315.820,2025-07-08,Credit Card,1,0.28,3789.56
4,C1376,Usman Lohano,Female,India,Mumbai,Electronics,Mouse,3,185.560,2024-08-01,PayPal,2,0.21,732.96
5,C1319,Hamza Brown,Male,Pakistan,Hyderabad,Books,SQL Book,4,502.600,2024-03-01,Cash,1,0.27,1467.59
6,C1145,Fatima Malik,Female,UAE,Abu Dhabi,Electronics,Mouse,5,442.640,2024-03-11,Credit Card,2,0.24,1682.03
7,C1529,Fatima Shah,Male,India,Pune,Clothing,Running Shoes,4,366.490,2024-03-11,Bank Transfer,1,0.18,1202.09
8,C1314,Fatima Patel,Male,India,Ahmedabad,Home & Kitchen,Headphones,2,1093.480,2024-03-11,Credit Card,1,0.18,1793.31
9,C1373,Usman Lohano,Male,Canada,Toronto,Electronics,Shoes,5,903.720,2024-03-11,Bank Transfer,1,0.03,4383.04

In [24]:
cleaned_file = "cleaned_ecommerce_data.csv"

df.to_csv(cleaned_file, index=False)

print("Cleaned dataset saved as:", cleaned_file)

Cleaned dataset saved as: cleaned_ecommerce_data.csv